### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by lammak** [Mr-Groch/PTVO-Zigbee-CC2530-PCF8583-counter#1]
Hello, thank you for this project.
I am trying make this project, but i stuck on .JS file where should add this file ? Can you share me screen ?

Thanks
L

**Comment by Mr-Groch** [comment]
Copy `ptvo.counter.js` to zigbee2mqtt configuration folder, edit if needed (to customize it for your needs) and next, if you're using Zigbee2MQTT as Home Assistant supervisor addon, then add to configuration tab:

![image](https://user-images.githubusercontent.com/20594810/138942105-4ff3ad29-43d7-4781-8f3c-fbcebe06effb.png)

If youre using zigbee2mqtt standalone, then add to your configuration file:

```
"external_converters": [
    "ptvo.counter.js"
  ]
```

**Comment by lammak** [comment]
Thank you working perfect :)
